In [54]:
!nvidia-smi

Fri Jan  2 14:32:18 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   74C    P0             32W /   70W |    1140MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import nltk
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


## Importing the pre-trained model from Transformers

In [46]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [47]:
model_name = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"


tokenizer = AutoTokenizer.from_pretrained(model_name)
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True, use_safetensors=False)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [48]:
# text = "i love all the features provided by euron"
text = "My name is Abhishek maity and i am a data scientist"

In [49]:
input = tokenizer(text, return_tensors="tf")
input

{'input_ids': <tf.Tensor: shape=(1, 17), dtype=int32, numpy=
array([[  101,  2026,  2171,  2003, 11113, 24158,  5369,  2243, 14736,
         3723,  1998,  1045,  2572,  1037,  2951,  7155,   102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 17), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [50]:
output = model(**input)
output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-2.914936 ,  3.0743227]], dtype=float32)>, hidden_states=None, attentions=None)

In [51]:
prob = tf.nn.softmax(output.logits, axis=-1).numpy()[0]
prob

array([0.00249926, 0.9975007 ], dtype=float32)

In [52]:
predict_class_id = np.argmax(prob)
predict_class_id

np.int64(1)

In [53]:
model.config.id2label[predict_class_id]

'POSITIVE'

## Pre-Trained Summarization model

In [55]:
from transformers import pipeline

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

ARTICLE = """ New York (CNN)When Liana Barrientos was 23 years old, she got married in Westchester County, New York.
A year later, she got married again in Westchester County, but to a different man and without divorcing her first husband.
Only 18 days after that marriage, she got hitched yet again. Then, Barrientos declared "I do" five more times, sometimes only within two weeks of each other.
In 2010, she married once more, this time in the Bronx. In an application for a marriage license, she stated it was her "first and only" marriage.
Barrientos, now 39, is facing two criminal counts of "offering a false instrument for filing in the first degree," referring to her false statements on the
2010 marriage license application, according to court documents.
Prosecutors said the marriages were part of an immigration scam.
On Friday, she pleaded not guilty at State Supreme Court in the Bronx, according to her attorney, Christopher Wright, who declined to comment further.
After leaving court, Barrientos was arrested and charged with theft of service and criminal trespass for allegedly sneaking into the New York subway through an emergency exit, said Detective
Annette Markowski, a police spokeswoman. In total, Barrientos has been married 10 times, with nine of her marriages occurring between 1999 and 2002.
All occurred either in Westchester County, Long Island, New Jersey or the Bronx. She is believed to still be married to four men, and at one time, she was married to eight men at once, prosecutors say.
Prosecutors said the immigration scam involved some of her husbands, who filed for permanent residence status shortly after the marriages.
Any divorces happened only after such filings were approved. It was unclear whether any of the men will be prosecuted.
The case was referred to the Bronx District Attorney\'s Office by Immigration and Customs Enforcement and the Department of Homeland Security\'s
Investigation Division. Seven of the men are from so-called "red-flagged" countries, including Egypt, Turkey, Georgia, Pakistan and Mali.
Her eighth husband, Rashid Rajput, was deported in 2006 to his native Pakistan after an investigation by the Joint Terrorism Task Force.
If convicted, Barrientos faces up to four years in prison.  Her next court appearance is scheduled for May 18.
"""
print(summarizer(ARTICLE, max_length=130, min_length=30, do_sample=False))

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0


[{'summary_text': 'Liana Barrientos, 39, is charged with two counts of "offering a false instrument for filing in the first degree" In total, she has been married 10 times, with nine of her marriages occurring between 1999 and 2002. She is believed to still be married to four men.'}]


In [56]:
from transformers import AutoTokenizer , AutoModelForSeq2SeqLM
model_name  = "facebook/nllb-200-distilled-600M"

In [57]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [58]:
input_text  ="""New York (CNN)When Liana Barrientos was 23 years old, she got married in Westchester County, New York.
A year later, she got married again in Westchester County, but to a different man and without divorcing her first husband.
Only 18 days after that marriage, she got hitched yet again. Then, Barrientos declared "I do" five more times, sometimes only within two weeks of each other.
In 2010, she married once more, this time in the Bronx. In an application for a marriage license, she stated it was her "first and only" marriage.
Barrientos, now 39, is facing two criminal counts of "offering a false instrument for filing in the first degree," referring to her false statements on the
2010 marriage license application, according to court documents.
Prosecutors said the marriages were part of an immigration scam.
On Friday, she pleaded not guilty at State Supreme Court in the Bronx, according to her attorney, Christopher Wright, who declined to comment further.
After leaving court, Barrientos was arrested and charged with theft of service and criminal trespass for allegedly sneaking into the New York subway through an emergency exit, said Detective
Annette Markowski, a police spokeswoman. In total, Barrientos has been married 10 times, with nine of her marriages occurring between 1999 and 2002.
All occurred either in Westchester County, Long Island, New Jersey or the Bronx. She is believed to still be married to four men, and at one time, she was married to eight men at once, prosecutors say.
Prosecutors said the immigration scam involved some of her husbands, who filed for permanent residence status shortly after the marriages.
Any divorces happened only after such filings were approved. It was unclear whether any of the men will be prosecuted.
The case was referred to the Bronx District Attorney\'s Office by Immigration and Customs Enforcement and the Department of Homeland Security\'s
Investigation Division. Seven of the men are from so-called "red-flagged" countries, including Egypt, Turkey, Georgia, Pakistan and Mali.
Her eighth husband, Rashid Rajput, was deported in 2006 to his native Pakistan after an investigation by the Joint Terrorism Task Force.
If convicted, Barrientos faces up to four years in prison.  Her next court appearance is scheduled for May 18."""



tokenizer.src_lang = "eng_Latn"
encoded  = tokenizer(input_text, return_tensors='pt')
encoded

{'input_ids': tensor([[256047,   4617,   9114,    104, 124723, 248098, 248161, 164972,   2370,
            125,   3937,    174,  19849,   1398,   2994,  12607,  13320, 248079,
           5889,   8324,  87740,    108,  23344,  42309,  77236, 248079,   4617,
           9114, 248075,     70,  17174,  27706, 248079,   5889,   8324,  87740,
          22730,    108,  23344,  42309,  77236, 248079,   3605,    202,      9,
          30158,    492,    540,  31494,  61632,  21289,   1929,  13417,  80487,
         248075,  67397,   1161,  26214,  16616,   1482, 120623, 248079,   5889,
           8324,   7840,  50038,   5563,  22730, 248075,  36918, 248079,   3937,
            174,  19849, 232694,     69, 248101,    359, 248108,  54369,   6780,
          38011, 248079, 103831,  12468,  39317,   9872,  66893,    452,  25026,
          10603, 248075,    717,  44951,   5889,  87740,  46171,   6780, 248079,
           3423,   6471,    108,    349, 121779, 248153, 248075,    717,    111,
          5857

In [59]:
output = model.generate(**encoded, forced_bos_token_id = tokenizer.convert_tokens_to_ids("bho_Deva"))
output

tensor([[     2, 256027, 235436,    104, 124723, 248098, 248161,   6855,    504,
            942,   7385,  16196,   2018,  21667, 248165,   2994,  11578,    483,
         158290, 248079,    352,    692, 235436,    483,   5855,   6460,   3675,
          64182, 190557, 248204,   7463,   1035,  97254,  33847, 248150, 248075,
           1224,  11578,   9197, 248079,    692,  13661,     69, 248202,   1766,
            660,    386, 130204, 248108,  97254,  33847, 248150, 248075,  10157,
           1224,  11578,   9197, 248079,    692,  16348,  68609,  67545,   1160,
          84547, 248133,   2648,  19042,    483,  32587, 115071,  51865,   1160,
         214270,  33847,    626, 248075,  13605,   1161,   6440,   9197,    692,
          97254,  33847, 248150, 248079,  10755,   1160,  97254,  33847, 248150,
         248075,  10755, 248079,  16196,   2018,  21667, 248165,  70951,  70162,
             69,  30046, 248108,    483,  63082,  33847,    626, 248079, 197306,
         248105, 248133,  52

In [60]:
tokenizer.batch_decode(output, skip_special_tokens=True)[0]


'न्यूयॉर्क (CNN) जब लियाना बैरींटस 23 साल के रहली, त उ न्यूयॉर्क के वेस्टचेस्टर काउंटी में शादी कइलन. एक साल बाद, उ आपन "पहिला आ एकमात्र" शादी कइलन. लेकिन एक साल बाद, उ अपना पहिला पति से तलाक लेबे के बिना दुसर आदमी से बियाह कइलें. बस 18 दिन बाद उ शादी कइलन, फिर से शादी कइलन. फिर, बैरींटस पांच बेर "हम" के घोषणा कइलें, कबो-कबो दू हफ्ता के भीतर एक दूसरा से. 2010 में, उ ब्रोंक्स में शादी कइलन. शादी के लाइसेंस के आवेदन में, उ कहलें कि ई उनकर "पहिला आ एकमात्र" शादी रहल. अब 39 साल के बैरींटस, "पहिला डिग्री में दाखिल करे खातिर झूठा उपकरण के पेशकश करे के दो आपराधिक मामला के सामना कर रहल बा", अदालत के दस्तावेज के अनुसार, उ'

## Loading IMDB Dataset for finetuning LLM Model

In [61]:
from datasets import load_dataset
dataset = load_dataset("imdb")
dataset

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [63]:
dataset["train"][1]


{'text': '"I Am Curious: Yellow" is a risible and pretentious steaming pile. It doesn\'t matter what one\'s political views are because this film can hardly be taken seriously on any level. As for the claim that frontal male nudity is an automatic NC-17, that isn\'t true. I\'ve seen R-rated films with male nudity. Granted, they only offer some fleeting views, but where are the R-rated films with gaping vulvas and flapping labia? Nowhere, because they don\'t exist. The same goes for those crappy cable shows: schlongs swinging in the breeze but not a clitoris in sight. And those pretentious indie movies like The Brown Bunny, in which we\'re treated to the site of Vincent Gallo\'s throbbing johnson, but not a trace of pink visible on Chloe Sevigny. Before crying (or implying) "double-standard" in matters of nudity, the mentally obtuse should take into account one unavoidably obvious anatomical difference between men and women: there are no genitals on display when actresses appears nude, 

In [65]:
type(dataset)

datasets.dataset_dict.DatasetDict

### Tokenizing the full imdb dataset

In [66]:
from transformers import AutoTokenizer

model_checkpoint = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def tokenizer_fn(data):
    return tokenizer(data["text"], padding="max_length", truncation=True)

tokenized_dataset = dataset.map(tokenizer_fn, batched=True)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [67]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 50000
    })
})

#### All the texts will be of different length, but the attention mask will always be same (512 in this case) for all the texts, as it pads all the texts into same size

In [68]:
len(tokenized_dataset["train"][0]["attention_mask"])

512

In [69]:
len(tokenized_dataset["train"][0]["text"].split())

288

In [70]:
len(tokenized_dataset["train"][70]["text"].split())

228

In [71]:
len(tokenized_dataset["train"][999]["text"].split())

266

#### We don't need text column, as we have already tokenized all the texts

In [73]:
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")
tokenized_dataset = tokenized_dataset.remove_columns("text")
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 50000
    })
})

##### setting the format to Pytorch format

In [74]:
tokenized_dataset.set_format("torch")

In [75]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=2)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [76]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./result", 
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    weight_decay=0.01
)

In [78]:
!pip install transformers[torch] accelerate>=0.26.0

### Starting the Fine Tuning of the LLM

In [84]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"].select(range(100)),
    eval_dataset=tokenized_dataset["test"].select(range(100))
)

trainer.train()

TrainOutput(global_step=13, training_loss=0.16187840241652268, metrics={'train_runtime': 12.8215, 'train_samples_per_second': 7.799, 'train_steps_per_second': 1.014, 'total_flos': 13246739865600.0, 'train_loss': 0.16187840241652268, 'epoch': 1.0})

In [85]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 50000
    })
})