# Vector Embeddings
1. ChromaDB
2. Pinecone
3. Weaviate
4. FAISS (Facebook AI Semantic Search)

### Embedding Generation - Euri

In [17]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "euri-9d4c27a7dac439c64b3fa10dfdddf6ac83eead90cf565f63da731391c2e8d3b5"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

text = "The food was delicious and the service was excellent."

data1 = generate_embeddings(text)

In [18]:
data2 = generate_embeddings("my name is Abhishek Maity")

In [19]:
data1, data2

(array([-0.03242217, -0.00837056, -0.06352426, ..., -0.00223515,
         0.05900396, -0.03150211]),
 array([ 3.0995198e-02, -3.2230254e-02,  2.2112282e-02, ...,
         7.5242770e-05,  4.4208606e-05,  1.2130879e-02]))

In [20]:
len(generate_embeddings("my name is Abhishek Maity"))

1536

### Cosine Similarity

In [21]:
cosine_similarity = np.dot(data1, data2)/ (np.linalg.norm(data1)*np.linalg.norm(data2))
cosine_similarity

np.float64(0.06961869806597601)

In [22]:
cosine_distance = 1 - cosine_similarity
cosine_distance

np.float64(0.930381301934024)

In [23]:
data3 = generate_embeddings("people call by my name Abhishek Maity")
data3

array([ 0.04484749, -0.0365818 ,  0.02437423, ..., -0.00608674,
        0.01644954,  0.01113003])

In [25]:
cosine_similarity = np.dot(data3, data2)/ (np.linalg.norm(data3)*np.linalg.norm(data2))

cosine_distance = 1 - cosine_similarity

print(cosine_similarity, cosine_distance)

0.8418239127856915 0.15817608721430854


ChromaDB always tries to find cosine similarity between 2 vectors, the lesser the angle >> the more similar 2 vectors are.
- Euclidean dist is calculated by sqrt(square(x2-x1) + square(y2-y1).... Nth)